websites:
  - url: https://www.pap.pl/kraj?page=0
    selector: .title

  - url: https://sport.um.warszawa.pl/waw/aktywna-warszawa/aktualnosci
    selector: .custom-list-page__item

  - url: https://www.wojsko-polskie.pl/sgwp/articles/list/aktualnosci-w/?strona=1
    selector: .newsgrid.hoverable





