websites:
  - url: https://www.wojsko-polskie.pl/dorsz/articles/news/
    selector: .opacityToTop
    link_selector: .opacityToTop a

  - url: https://forsal.pl/kraj/bezpieczenstwo
    selector: .listItem.listItemSolr.itarticle
    link_selector: .listItem.listItemSolr.itarticle a

  - url: https://www.polskieradio.pl/399/8097
    selector: .article
    link_selector: .article a

  - url: https://www.bbn.gov.pl/pl/wydarzenia
    selector: .okno li
    link_selector: .okno li a

  - url: https://en.bbn.gov.pl/en/news
    selector: .okno li
    link_selector: .okno li a

  - url: https://www.gov.pl/web/diplomacy/news-
    selector: .title
    link_selector: .title a

  - url: https://www.pap.pl/kraj
    selector: .title
    link_selector: .title a

  - url: https://www.polskieradio.pl/399/8097
    selector: .article
    link_selector: .article a

  - url: https://www.polskieradio.pl/399/7978
    selector: .article
    link_selector: .article a

  - url: https://www.polskieradio.pl/399/7977
    selector: .article
    link_selector: .article a

  - url: https://www.polskieradio.pl/399/8174
    selector: .article
    link_selector: .article a

  - url: https://www.polskieradio.pl/399/8173
    selector: .article
    link_selector: .article a

  - url: https://www.polskieradio.pl/395/7789
    selector: .article
    link_selector: .article a

  - url: https://www.polskieradio.pl/395/7785
    selector: .article
    link_selector: .article a

  - url: https://www.polskieradio.pl/395/7784
    selector: .article
    link_selector: .article a

  - url: https://www.pap.pl/en/world?page=0
    selector: .title

  - url: https://www.polskieradio.pl/395/7782
    selector: .article
    link_selector: .article a

  - url: https://www.pap.pl/en/poland?page=0
    selector: .title

  - url: https://www.wojsko-polskie.pl/dgrsz/articles/news/
    selector: .newsgrid.hoverable

  - url: https://www.wojsko-polskie.pl/kgzw/articles/list/aktualnosci-w/
    selector: .newsgrid.hoverable

  - url: https://www.wojsko-polskie.pl/sgwp/articles/list/aktualnosci-w/?strona=1
    selector: .newsgrid.hoverable

  - url: https://media.terytorialsi.wp.mil.pl/informacje
    selector: .tile-js-link.clamp-3
    link_selector: .tile-js-link.clamp-3 a

  - url: https://www.wojsko-polskie.pl/articles/news/
    selector: .text
    link_selector: .text a  

  - url: https://zbiam.pl/news/
    selector: .oxy-post
    link_selector: .oxy-post a

  - url: https://www.gov.pl/web/premier/wydarzenia
    selector: .title
    link_selector: .title a

  - url: https://www.gov.pl/web/obrona-narodowa/aktualnosci5
    selector: .title
    link_selector: .title a

  - url: https://www.gov.pl/web/national-defence/news
    selector: .title
    link_selector: .title a


























